version: 2

updates:
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'weekly'
      timezone: 'Asia/Tokyo'
    target-branch: 'main'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      timezone: 'Asia/Tokyo'
    target-branch: 'main'
